name: 02 - Workflow Events

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/5 0 * * *' 
    
jobs:

    echo:
          runs-on: ubuntu-latest
          steps:
            - name: Show the triggering event
              run: echo "This workflow was triggered by a(n) ${{ github.event_name }} event."
