name: 02 - Workflow Events

on: 
  push:
    
jobs:

        eho:
          runs-on: ubuntu-latest
          steps:
            - name: Show the triggering event
              run: echo "This workflow was triggered by a(n) ${{ github.event_name }} event."
